name: Build Index & Action Pages
on: [push]

jobs:
  pages-directory-listing:
    runs-on: ubuntu-latest
    name: Run Actions Template
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Directory Listings
        uses: jayanta525/github-pages-directory-listing@v4.0.0
        with:
          FOLDER: '.'

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1

  deploy:
    needs: pages-directory-listing
    permissions:
      contents: write
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
